spring:
  profiles:
    active: dev
    
---
spring:
     profiles: dev
     application:
       name: microservice-config-dev02

---
spring:
     profiles: test
     application:
       name: microservice-config-test


